let maxNumb=0;function doTest(){this.disabled=!0;let e=document.querySelectorAll("p");e.forEach(e=>{if(/^\d+\./.test(e.innerText)){let n=e.innerText.match(/\d+/)[0];maxNumb=Math.max(maxNumb,+n);let t=e.nextElementSibling,a=/…+/;if(/^\d+(\s)*(?=.*\bA\.(\s)*)(?=.*\bB\.(\s)*)(?=.*\bC\.(\s)*)(?=.*\bD\.(\s)*).*$/.test(e.innerText)){let l=e.innerText.trim().replace("A.","}~").replace("B.","}~").replace("C.","}~").replace("D.","}~").split(/(\s)*}~(\s)*/).filter(e=>e&&e?.length&&!!/\S/.test(e));for(i=0,e.innerHTML=n+".<br>";i<4;i++){let r=String.fromCharCode(i+65);e.innerHTML+=`
        <input type="radio" name ="${n}" value="${r}" id="${n+r}">
        <label for="${n+r}">${r+". "+l[i+1]}</label><br>
        `}}else if(/^(?=.*\bA\.(\s)*)(?=.*\bB\.(\s)*)(?=.*\bC\.(\s)*)(?=.*\bD\.(\s)*).*$/.test(t.innerText.replaceAll("\n"," "))){let d=t.innerHTML.replaceAll("&nbsp;"," ").trim().replace("A.","}~").replace("B.","}~").replace("C.","}~").replace("D.","}~").split(/(\s)*}~(\s)*/).filter(e=>e&&e?.length&&!!/\S/.test(e));for(i=0,t.innerHTML="";i<4;i++){let p=String.fromCharCode(i+65);t.innerHTML+=`
        <input type="radio" name ="${n}" value="${p}" id="${n+p}">
        <label for="${n+p}">${p+". "+d[i]}</label><br>
        `}}else a.test(e.innerText)?e.innerHTML=e.innerHTML.replace(/…+\.?\.?/,`<input type = "text" id="A${n}" style="border:0;outline:0; border-bottom: 1px dotted;background: #f4f4f4;" oninput="this.size = Math.max(this.value.length,20)" autocomplete="off"/>`):a.test(t.innerText)?t.innerHTML=t.innerHTML.replace(/…+\.?\.?/,`<input type = "text" id="A${n}" style="border:0;outline:0; border-bottom: 1px dotted;background: #f4f4f4;" oninput="this.size = Math.max(this.value.length,20)" autocomplete="off"/>`):/^\d+(\s)*(?=.*\bA\)(\s)*)(?=.*\bB\)(\s)*)(?=.*\bC\)(\s)*)(?=.*\bD\)(\s)*).*$/.test(e.innerText)&&(e.innerHTML=e.innerHTML.replace("(A)",`<input type="radio" name ="${n}" value="A" id="${n+"A"}">
        <label for="${n+"A"}">(A)`),e.innerHTML=e.innerHTML.replace("(B)",`<input type="radio" name ="${n}" value="B" id="${n+"B"}">
        <label for="${n+"B"}">(B)`),e.innerHTML=e.innerHTML.replace("(C)",`<input type="radio" name ="${n}" value="C" id="${n+"C"}">
        <label for="${n+"C"}">(C)`),e.innerHTML=e.innerHTML.replace("(D)",`<input type="radio" name ="${n}" value="D" id="${n+"D"}">
        <label for="${n+"D"}">(D)`),e.innerHTML=e.innerHTML.replaceAll("</span>","</span></label>"))}})}function guiDapAn(){let e={year:madethi};for(i=1;i<=maxNumb;i++)try{document.getElementById(i+"A").checked?e["cau"+i]="A":document.getElementById(i+"B").checked?e["cau"+i]="B":document.getElementById(i+"C").checked?e["cau"+i]="C":document.getElementById(i+"D").checked&&(e["cau"+i]="D")}catch(n){e["cau"+i]=document.getElementById("A"+i)?.value}fetch("http://localhost:3003/api/data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(e)}).then(e=>e.json()).then(e=>hienDiem(e)).catch(e=>console.error(e))}function hienDiem(e){document.getElementById("dapAn").innerHTML="<p> Điểm: "+e.diem+"</p>",document.getElementById("dapAn").innerHTML+="<p> Số c\xe2u đ\xfang: "+e.socaudung+"</p>",document.getElementById("dapAn").innerHTML+="<p> Số c\xe2u sai: "+e.socausai+"</p>",document.getElementById("dapAn").innerHTML+="<p> Số c\xe2u đ\xe3 l\xe0m: "+e.socaudalam+"/"+maxNumb+"</p>",document.getElementById("dapAn").innerHTML+="<p> Số c\xe2u chưa l\xe0m: "+e.socauchualam+"/"+maxNumb+"</p>"}location.href.includes("huongdan.online")&&(document.getElementById("doTest").addEventListener("click",doTest),document.getElementById("chamdiem").addEventListener("click",hienDiem));
