const str=window.location.href,regex=/\b\d{4}\b/g,matches=str.match(regex),madethi=matches[0],scriptTag=document.createElement("script");scriptTag.src=`https://cdn.jsdelivr.net/gh/onlincode/hdo/ansts10anhhcm${madethi}.js`;const element=document.getElementById("dapAn");element.insertAdjacentElement("afterend",scriptTag);const countdownBtn=document.getElementById("doTest");let maxNumb=0;function doTest(){try{this.disabled=!0;let e=3600,t=setInterval(function(){if(--e<=0)clearInterval(t),alert("Đ\xe3 hết giờ l\xe0m b\xe0i"),guiDapAn(),countdownBtn.innerText="Bắt đầu l\xe0m b\xe0i",countdownBtn.disabled=!1;else{let n=Math.floor(e/60),r=e%60;countdownBtn.innerText=`C\xf2n ${n} p :${r.toString().padStart(2,"0")} s`}},1e3),n=document.querySelectorAll("p");n.forEach(e=>{let t=/^\d+\./;if(t.test(e.innerText)){let n=e.innerText.match(/\d+/)[0];n||(n=maxNumb),maxNumb=Math.max(maxNumb,+n);let r=e.nextElementSibling,a=/…+/;if(/^\d+(\s)*(?=.*\bA\.(\s)*)(?=.*\bB\.(\s)*)(?=.*\bC\.(\s)*)(?=.*\bD\.(\s)*).*$/.test(e.innerText)){let l=e.innerText.trim().replace("A.","}~").replace("B.","}~").replace("C.","}~").replace("D.","}~").split(/(\s)*}~(\s)*/).filter(e=>e&&""!=e&&!!/\S/.test(e));for(i=0,e.innerHTML=n+".<br>";i<4;i++){let c=String.fromCharCode(i+65);e.innerHTML+=`
            <input type="radio" name ="${n}" value="${c}" id="${n+c}">
            <label for="${n+c}">${c+". "+l[i+1]}</label><br>
            `}}else if(/^(?=.*\bA\.(\s)*)(?=.*\bB\.(\s)*)(?=.*\bC\.(\s)*)(?=.*\bD\.(\s)*).*$/.test(r.innerText.replace(/\n/g," "))){let s=r.innerHTML.replace(/&nbsp;/g," ").trim().replace("A.","}~").replace("B.","}~").replace("C.","}~").replace("D.","}~").split(/(\s)*}~(\s)*/).filter(e=>e&&""!=e&&!!/\S/.test(e));for(i=0,r.innerHTML="";i<4;i++){let d=String.fromCharCode(i+65);r.innerHTML+=`
            <input type="radio" name ="${n}" value="${d}" id="${n+d}">
            <label for="${n+d}">${d+". "+s[i]}</label><br>
            `}}else a.test(e.innerText)?e.innerHTML=e.innerHTML.replace(/…+\.?\.?/,`<input type = "text" id="A${n}" style="border:0;outline:0; border-bottom: 1px dotted;background: #f4f4f4;" oninput="this.size = Math.max(this.value.length,20)" autocomplete="off"/>`):a.test(r.innerText)&&!t.test(r.innerText)?r.innerHTML=r.innerHTML.replace(/…+\.?\.?/,`<input type = "text" id="A${n}" style="border:0;outline:0; border-bottom: 1px dotted;background: #f4f4f4;" oninput="this.size = Math.max(this.value.length,20)" autocomplete="off"/>`):/^\d+(\s)*(?=.*\bA\)(\s)*)(?=.*\bB\)(\s)*)(?=.*\bC\)(\s)*)(?=.*\bD\)(\s)*).*$/.test(e.innerText)&&(e.innerHTML=e.innerHTML.replace("(A)",`<input type="radio" name ="${n}" value="A" id="${n+"A"}">
            <label for="${n+"A"}">(A)`),e.innerHTML=e.innerHTML.replace("(B)",`<input type="radio" name ="${n}" value="B" id="${n+"B"}">
            <label for="${n+"B"}">(B)`),e.innerHTML=e.innerHTML.replace("(C)",`<input type="radio" name ="${n}" value="C" id="${n+"C"}">
            <label for="${n+"C"}">(C)`),e.innerHTML=e.innerHTML.replace("(D)",`<input type="radio" name ="${n}" value="D" id="${n+"D"}">
            <label for="${n+"D"}">(D)`),e.innerHTML=e.innerHTML.replace(/<\/span>/g,"</span></label>"))}})}catch(r){alert(r)}}function guiDapAn(){try{let e={madethi:madethi};for(i=1;i<=maxNumb;i++)try{document.getElementById(i+"A").checked?e["cau"+i]="A":document.getElementById(i+"B").checked?e["cau"+i]="B":document.getElementById(i+"C").checked?e["cau"+i]="C":document.getElementById(i+"D").checked&&(e["cau"+i]="D")}catch(t){e["cau"+i]=document.getElementById("A"+i).value,""==e["cau"+i]&&delete e["cau"+i]}hienDiem(checkFull(e))}catch(n){alert(n)}}function hienDiem(e){e.error||(document.getElementById("dapAn").innerHTML="<p> Điểm: "+e.diem+"</p>",document.getElementById("dapAn").innerHTML+="<p> Số c\xe2u đ\xfang: "+e.socaudung+"</p>",document.getElementById("dapAn").innerHTML+="<p> Số c\xe2u sai: "+e.socausai+"</p>",document.getElementById("dapAn").innerHTML+="<p> Số c\xe2u đ\xe3 l\xe0m: "+e.socaudalam+"/"+maxNumb+"</p>",document.getElementById("dapAn").innerHTML+="<p> Số c\xe2u chưa l\xe0m: "+e.socauchualam+"/"+maxNumb+"</p>")}location.href.includes("huongdan.online")&&(document.getElementById("doTest").addEventListener("click",doTest),document.getElementById("chamdiem").addEventListener("click",guiDapAn));const checkFull=e=>{console.log(e);var t=0,n=0,r=0,a=0,l=40;for(var c of Object.keys(e))if("madethi"==c);else try{temp=checkingFunctions["check"+c]({userAns:e[c]}),t+=temp,n++,l--,temp?r++:a++}catch(s){}return{diem:t,socaudalam:n,socaudung:r,socausai:a,socauchualam:l}},helperFunction=(e,t,n={})=>{var r=e.userAns.trim().split(/\s+/).join(" ").trim();if("ABCD"==n.type||1==t.length)return r==t;if("truefalse"==n.type||"True"==t||"False"==t)return r==t||r==t+"."||r==t+" ."||r==t.toLowerCase()||r==t.toLowerCase()+"."||r==t.toLowerCase()+" ."||r==t.toUpperCase()||r==t.toUpperCase()+"."||r==t.toUpperCase()+" .";return n.endingMark?r==t+" "+n.endingMark||r==t+n.endingMark:r==t||r==t+"."||r==t+" ."};
