const str=window.location.href,regex=/\b\d{4}\b/g,matches=str.match(regex),madethi=matches[0],countdownBtn=document.getElementById("doTest");let maxNumb=0;function doTest(){try{this.disabled=!0;let e=3600,t=setInterval(function(){if(--e<=0)clearInterval(t),alert("Đ\xe3 hết giờ l\xe0m b\xe0i"),guiDapAn(),countdownBtn.innerText="Bắt đầu l\xe0m b\xe0i",countdownBtn.disabled=!1;else{let n=Math.floor(e/60),a=e%60;countdownBtn.innerText=`C\xf2n ${n} p :${a.toString().padStart(2,"0")} s`}},1e3),n=document.querySelectorAll("p");n.forEach(e=>{let t=/^\d+\./;if(t.test(e.innerText)){let n=e.innerText.match(/\d+/)[0];n||(n=maxNumb),maxNumb=Math.max(maxNumb,+n);let a=e.nextElementSibling,r=/…+/;if(/^\d+(\s)*(?=.*\bA\.(\s)*)(?=.*\bB\.(\s)*)(?=.*\bC\.(\s)*)(?=.*\bD\.(\s)*).*$/.test(e.innerText)){let l=e.innerText.trim().replace("A.","}~").replace("B.","}~").replace("C.","}~").replace("D.","}~").split(/(\s)*}~(\s)*/).filter(e=>e&&""!=e&&!!/\S/.test(e));for(i=0,e.innerHTML=n+".<br>";i<4;i++){let d=String.fromCharCode(i+65);e.innerHTML+=`
            <input type="radio" name ="${n}" value="${d}" id="${n+d}">
            <label for="${n+d}">${d+". "+l[i+1]}</label><br>
            `}}else if(/^(?=.*\bA\.(\s)*)(?=.*\bB\.(\s)*)(?=.*\bC\.(\s)*)(?=.*\bD\.(\s)*).*$/.test(a.innerText.replace(/\n/g," "))){let o=a.innerHTML.replace(/&nbsp;/g," ").trim().replace("A.","}~").replace("B.","}~").replace("C.","}~").replace("D.","}~").split(/(\s)*}~(\s)*/).filter(e=>e&&""!=e&&!!/\S/.test(e));for(i=0,a.innerHTML="";i<4;i++){let c=String.fromCharCode(i+65);a.innerHTML+=`
            <input type="radio" name ="${n}" value="${c}" id="${n+c}">
            <label for="${n+c}">${c+". "+o[i]}</label><br>
            `}}else r.test(e.innerText)?e.innerHTML=e.innerHTML.replace(/…+\.?\.?/,`<input type = "text" id="A${n}" autocapitalize="off" style="border:0;outline:0; border-bottom: 1px dotted;background: #f4f4f4;" oninput="this.size = Math.max(this.value.length,20)" autocomplete="off"/>`):r.test(a.innerText)&&!t.test(a.innerText)?a.innerHTML=a.innerHTML.replace(/…+\.?\.?/,`<input type = "text" id="A${n}" autocapitalize="off" style="border:0;outline:0; border-bottom: 1px dotted;background: #f4f4f4;" oninput="this.size = Math.max(this.value.length,20)" autocomplete="off"/>`):/^\d+(\s)*(?=.*\bA\)(\s)*)(?=.*\bB\)(\s)*)(?=.*\bC\)(\s)*)(?=.*\bD\)(\s)*).*$/.test(e.innerText)&&(e.innerHTML=e.innerHTML.replace("(A)",`<input type="radio" name ="${n}" value="A" id="${n+"A"}">
            <label for="${n+"A"}">(A)`),e.innerHTML=e.innerHTML.replace("(B)",`<input type="radio" name ="${n}" value="B" id="${n+"B"}">
            <label for="${n+"B"}">(B)`),e.innerHTML=e.innerHTML.replace("(C)",`<input type="radio" name ="${n}" value="C" id="${n+"C"}">
            <label for="${n+"C"}">(C)`),e.innerHTML=e.innerHTML.replace("(D)",`<input type="radio" name ="${n}" value="D" id="${n+"D"}">
            <label for="${n+"D"}">(D)`),e.innerHTML=e.innerHTML.replace(/<\/span>/g,"</span></label>"))}})}catch(a){alert(a)}}function guiDapAn(){try{let e={madethi:`ts10anhhcm${madethi}`};for(i=1;i<=maxNumb;i++)try{document.getElementById(i+"A").checked?e["cau"+i]="A":document.getElementById(i+"B").checked?e["cau"+i]="B":document.getElementById(i+"C").checked?e["cau"+i]="C":document.getElementById(i+"D").checked&&(e["cau"+i]="D")}catch(t){e["cau"+i]=document.getElementById("A"+i).value,""==e["cau"+i]&&delete e["cau"+i]}fetch("https://code.huongdan.online/api/data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(e)}).then(e=>e.json()).then(hienDiem).catch(alert)}catch(n){alert(n)}}function hienDiem(e){e.error||(document.getElementById("dapAn").innerHTML="<p> Điểm: "+e.diem+"</p>",document.getElementById("dapAn").innerHTML+="<p> Số c\xe2u đ\xfang: "+e.socaudung+"</p>",document.getElementById("dapAn").innerHTML+="<p> Số c\xe2u sai: "+e.socausai+"</p>",document.getElementById("dapAn").innerHTML+="<p> Số c\xe2u đ\xe3 l\xe0m: "+e.socaudalam+"/"+(e.maxNumb?e.maxNumb:maxNumb)+"</p>",document.getElementById("dapAn").innerHTML+="<p> Số c\xe2u chưa l\xe0m: "+e.socauchualam+"/"+(e.maxNumb?e.maxNumb:maxNumb)+"</p>")}location.href.includes("huongdan.online")&&(document.getElementById("doTest").addEventListener("click",doTest),document.getElementById("chamdiem").addEventListener("click",guiDapAn));
